//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7-b63 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.29 at 10:30:00 AM EST 
//


package ca.gc.cra.fxit.xmlt.transformation.jaxb.etr;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for EtrBizActivityType_EnumType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="EtrBizActivityType_EnumType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="ETR501"/>
 *     &lt;enumeration value="ETR502"/>
 *     &lt;enumeration value="ETR503"/>
 *     &lt;enumeration value="ETR504"/>
 *     &lt;enumeration value="ETR505"/>
 *     &lt;enumeration value="ETR506"/>
 *     &lt;enumeration value="ETR507"/>
 *     &lt;enumeration value="ETR508"/>
 *     &lt;enumeration value="ETR509"/>
 *     &lt;enumeration value="ETR510"/>
 *     &lt;enumeration value="ETR511"/>
 *     &lt;enumeration value="ETR512"/>
 *     &lt;enumeration value="ETR513"/>
 *     &lt;enumeration value="ETR514"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "EtrBizActivityType_EnumType")
@XmlEnum
public enum EtrBizActivityTypeEnumType {


    /**
     * Research and Development
     * 
     */
    @XmlEnumValue("ETR501")
    ETR_501("ETR501"),

    /**
     * Holding or Managing intellectual property
     * 
     */
    @XmlEnumValue("ETR502")
    ETR_502("ETR502"),

    /**
     * Purchasing or Procurement
     * 
     */
    @XmlEnumValue("ETR503")
    ETR_503("ETR503"),

    /**
     * Manufacturing or Production
     * 
     */
    @XmlEnumValue("ETR504")
    ETR_504("ETR504"),

    /**
     * Sales, Marketing or Distribution
     * 
     */
    @XmlEnumValue("ETR505")
    ETR_505("ETR505"),

    /**
     * Administrative, Management or Support Services
     * 
     */
    @XmlEnumValue("ETR506")
    ETR_506("ETR506"),

    /**
     * Provision of Services to unrelated parties
     * 
     */
    @XmlEnumValue("ETR507")
    ETR_507("ETR507"),

    /**
     * Internal Group Finance
     * 
     */
    @XmlEnumValue("ETR508")
    ETR_508("ETR508"),

    /**
     * Regulated Financial Services
     * 
     */
    @XmlEnumValue("ETR509")
    ETR_509("ETR509"),

    /**
     * Insurance
     * 
     */
    @XmlEnumValue("ETR510")
    ETR_510("ETR510"),

    /**
     * Holding shares or other equity instruments
     * 
     */
    @XmlEnumValue("ETR511")
    ETR_511("ETR511"),

    /**
     * Dormant
     * 
     */
    @XmlEnumValue("ETR512")
    ETR_512("ETR512"),

    /**
     * E-Commerce
     * 
     */
    @XmlEnumValue("ETR513")
    ETR_513("ETR513"),

    /**
     * Other
     * 
     */
    @XmlEnumValue("ETR514")
    ETR_514("ETR514");
    private final String value;

    EtrBizActivityTypeEnumType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static EtrBizActivityTypeEnumType fromValue(String v) {
        for (EtrBizActivityTypeEnumType c: EtrBizActivityTypeEnumType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
