//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7-b63 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.29 at 10:30:00 AM EST 
//


package ca.gc.cra.fxit.xmlt.transformation.jaxb.etr;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for EtrLegalBasisType_EnumType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="EtrLegalBasisType_EnumType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="ETR801"/>
 *     &lt;enumeration value="ETR802"/>
 *     &lt;enumeration value="ETR803"/>
 *     &lt;enumeration value="ETR804"/>
 *     &lt;enumeration value="ETR805"/>
 *     &lt;enumeration value="ETR806"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "EtrLegalBasisType_EnumType")
@XmlEnum
public enum EtrLegalBasisTypeEnumType {


    /**
     * Multilateral Convention on Mutual Administrative Assistance in Tax Matters
     * 
     */
    @XmlEnumValue("ETR801")
    ETR_801("ETR801"),

    /**
     * EU Council Directive 2011/16/EU
     * 
     */
    @XmlEnumValue("ETR802")
    ETR_802("ETR802"),

    /**
     * Double taxation treaty
     * 
     */
    @XmlEnumValue("ETR803")
    ETR_803("ETR803"),

    /**
     * Tax information exchange agreement
     * 
     */
    @XmlEnumValue("ETR804")
    ETR_804("ETR804"),

    /**
     * Nordic Mutual Assistance Convention
     * 
     */
    @XmlEnumValue("ETR805")
    ETR_805("ETR805"),

    /**
     * Other legal basis
     * 
     */
    @XmlEnumValue("ETR806")
    ETR_806("ETR806");
    private final String value;

    EtrLegalBasisTypeEnumType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static EtrLegalBasisTypeEnumType fromValue(String v) {
        for (EtrLegalBasisTypeEnumType c: EtrLegalBasisTypeEnumType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
