//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7-b63 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.29 at 10:30:00 AM EST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "urn:oecd:ties:etr:v1", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package ca.gc.cra.fxit.xmlt.transformation.jaxb.etr;
