//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.12 at 03:19:34 PM EST 
//


package ca.gc.cra.fxit.xmlt.transformation.jaxb.statusmessage;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CrsMessageStatus_Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CrsMessageStatus_Type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="OriginalMessage" type="{urn:oecd:ties:csm:v1}OriginalMessage_Type"/>
 *         &lt;element name="ValidationErrors" type="{urn:oecd:ties:csm:v1}ValidationErrors_Type"/>
 *         &lt;element name="ValidationResult" type="{urn:oecd:ties:csm:v1}ValidationResult_Type"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CrsMessageStatus_Type", propOrder = {
    "originalMessage",
    "validationErrors",
    "validationResult"
})
public class CrsMessageStatusType {

    @XmlElement(name = "OriginalMessage", required = true)
    protected OriginalMessageType originalMessage;
    @XmlElement(name = "ValidationErrors", required = true)
    protected ValidationErrorsType validationErrors;
    @XmlElement(name = "ValidationResult", required = true)
    protected ValidationResultType validationResult;

    /**
     * Gets the value of the originalMessage property.
     * 
     * @return
     *     possible object is
     *     {@link OriginalMessageType }
     *     
     */
    public OriginalMessageType getOriginalMessage() {
        return originalMessage;
    }

    /**
     * Sets the value of the originalMessage property.
     * 
     * @param value
     *     allowed object is
     *     {@link OriginalMessageType }
     *     
     */
    public void setOriginalMessage(OriginalMessageType value) {
        this.originalMessage = value;
    }

    /**
     * Gets the value of the validationErrors property.
     * 
     * @return
     *     possible object is
     *     {@link ValidationErrorsType }
     *     
     */
    public ValidationErrorsType getValidationErrors() {
        return validationErrors;
    }

    /**
     * Sets the value of the validationErrors property.
     * 
     * @param value
     *     allowed object is
     *     {@link ValidationErrorsType }
     *     
     */
    public void setValidationErrors(ValidationErrorsType value) {
        this.validationErrors = value;
    }

    /**
     * Gets the value of the validationResult property.
     * 
     * @return
     *     possible object is
     *     {@link ValidationResultType }
     *     
     */
    public ValidationResultType getValidationResult() {
        return validationResult;
    }

    /**
     * Sets the value of the validationResult property.
     * 
     * @param value
     *     allowed object is
     *     {@link ValidationResultType }
     *     
     */
    public void setValidationResult(ValidationResultType value) {
        this.validationResult = value;
    }

}
