//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.12 at 03:19:34 PM EST 
//


package ca.gc.cra.fxit.xmlt.transformation.jaxb.statusmessage;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for OriginalMessage_Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="OriginalMessage_Type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="OriginalMessageRefID" type="{urn:oecd:ties:csm:v1}StringMax200Type"/>
 *         &lt;element name="FileMetaData" type="{urn:oecd:ties:csm:v1}FileMetaData_Type" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OriginalMessage_Type", propOrder = {
    "originalMessageRefID",
    "fileMetaData"
})
public class OriginalMessageType {

    @XmlElement(name = "OriginalMessageRefID", required = true)
    protected String originalMessageRefID;
    @XmlElement(name = "FileMetaData")
    protected FileMetaDataType fileMetaData;

    /**
     * Gets the value of the originalMessageRefID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOriginalMessageRefID() {
        return originalMessageRefID;
    }

    /**
     * Sets the value of the originalMessageRefID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOriginalMessageRefID(String value) {
        this.originalMessageRefID = value;
    }

    /**
     * Gets the value of the fileMetaData property.
     * 
     * @return
     *     possible object is
     *     {@link FileMetaDataType }
     *     
     */
    public FileMetaDataType getFileMetaData() {
        return fileMetaData;
    }

    /**
     * Sets the value of the fileMetaData property.
     * 
     * @param value
     *     allowed object is
     *     {@link FileMetaDataType }
     *     
     */
    public void setFileMetaData(FileMetaDataType value) {
        this.fileMetaData = value;
    }

}
