//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.12 at 03:19:34 PM EST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "urn:oecd:ties:csm:v1", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED,
xmlns = { 
		@javax.xml.bind.annotation.XmlNs(namespaceURI = "urn:oecd:ties:csm:v1", prefix = "csm"),
		@javax.xml.bind.annotation.XmlNs(namespaceURI = "http://www.w3.org/2001/XMLSchema-instance", prefix = "xsd"),
		@javax.xml.bind.annotation.XmlNs(namespaceURI = "urn:oecd:ties:isocsmtypes:v1", prefix = "iso")
		}
)
package ca.gc.cra.fxit.xmlt.transformation.jaxb.statusmessage;
