//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.12 at 03:19:34 PM EST 
//


package ca.gc.cra.fxit.xmlt.transformation.jaxb.statusmessage;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ValidationResult_Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ValidationResult_Type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Status" type="{urn:oecd:ties:csm:v1}FileAcceptanceStatus_EnumType"/>
 *         &lt;element name="ValidatedBy" type="{urn:oecd:ties:csm:v1}StringMax400Type" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ValidationResult_Type", propOrder = {
    "status",
    "validatedBy"
})
public class ValidationResultType {

    @XmlElement(name = "Status", required = true)
    protected FileAcceptanceStatusEnumType status;
    @XmlElement(name = "ValidatedBy", required = true)
    protected List<String> validatedBy;

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link FileAcceptanceStatusEnumType }
     *     
     */
    public FileAcceptanceStatusEnumType getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link FileAcceptanceStatusEnumType }
     *     
     */
    public void setStatus(FileAcceptanceStatusEnumType value) {
        this.status = value;
    }

    /**
     * Gets the value of the validatedBy property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the validatedBy property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getValidatedBy().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getValidatedBy() {
        if (validatedBy == null) {
            validatedBy = new ArrayList<String>();
        }
        return this.validatedBy;
    }

}
