package ca.gc.cra.fxit.xmlt.transformation.cob2java.crs;
import ca.gc.ccra.rccr.cobol.*;
import java.util.*;

/** GENERATED BY COB2JAVA.
	MANUAL MAINTENANCE IS NOT RECOMMENDED

	<pre>
	Record Layout:

	  Offset  Length  Occ  Type Name
	  ======  ======  ===  ==== ==========================
		0		26		1	G	Prt18SlipInfo
		0		4		1	9		TransCd
		4		13		1	X		InfodecPsn
		17		9		1	X		SlpSqnbr
	</pre>
	@see rccr.cobol.CobolRecord
*/

@SuppressWarnings({"all"})
public class IP6MSGSL extends CobolRecord
{
	private static HashMap h = new HashMap();

	private static TreeSet fields = new TreeSet(new MVComparator());

	private static int fieldCount = 0;
	private static void put( CobolField f ) {
		h.put(f.getName(), new MapValue( fieldCount++, f ));
	}

	private static void init0() {
		put(new CobolField("Prt18SlipInfo",0,26,null,true));
		put(new CFNumeric("TransCd",0,4,null,0));
		put(new CobolField("InfodecPsn",4,13,null,false));
		put(new CobolField("SlpSqnbr",17,9,null,false));
	}

	static { 
		init0();
		fields.addAll(h.values());
	}

	public IP6MSGSL()
	{
		super(h, fields);
		rec = new byte[26];

		initialize();
	}

	public String getPrt18SlipInfo() { 
		return getString("Prt18SlipInfo");
	}

	public void setPrt18SlipInfo( String val ) { 
		set( "Prt18SlipInfo", val.trim() );
	}

	public int getTransCd() { 
		return getInt("TransCd");
	}

	public void setTransCd( int val ) { 
		set( "TransCd", val );
	}

	public String getInfodecPsn() { 
		return getString("InfodecPsn");
	}

	public void setInfodecPsn( String val ) { 
		set( "InfodecPsn", val.trim() );
	}

	public String getSlpSqnbr() { 
		return getString("SlpSqnbr");
	}

	public void setSlpSqnbr( String val ) { 
		set( "SlpSqnbr", val.trim() );
	}

	public String toString(){
		StringBuilder sb = new StringBuilder();
		
		sb
		.append("\n" + this.getClass().getSimpleName()+ ":infoDecPsn=").append(this.getInfodecPsn()).append(",")
		.append("getPrt18SlipInfo=").append(this.getPrt18SlipInfo().trim()).append(",")
		.append("getSlpSqnbr=").append(this.getSlpSqnbr().trim()).append(",")
		.append("getTransCd=").append(this.getTransCd())
		;
		
		return sb.toString();
	}
}