package ca.gc.cra.fxit.xmlt.transformation.cob2java.crs;
import ca.gc.ccra.rccr.cobol.*;
import java.util.*;

/** GENERATED BY COB2JAVA.
	MANUAL MAINTENANCE IS NOT RECOMMENDED

	<pre>
	Record Layout:

	  Offset  Length  Occ  Type Name
	  ======  ======  ===  ==== ==========================
		0		338		1	G	Prt18SummInfo
		0		4		1	9		TransCd
		4		2		1	X		RtnRcpntCntryCd
		6		13		1	X		InfodecPsn
		19		9		1	X		RtnSummTcd
		28		2		1	X		RtnTcd
		30		4		1	X		RtnTxYr
		34		103		1	G		ReportingFiGrp
		34		1		1	X			FiInfoDtyCd
		35		40		1	X			FiDocRefId
		75		40		1	X			FiCorrDocRefId
		115		2		1	X			FiRsdCntryCd
		117		20		1	X			FiGiin
		137		70		1	G		ReportingFiNameGrp
		137		35		1	X			FilrNmFrstTxt
		172		35		1	X			FilrNmSecTxt
		207		131		1	G		ReportingFiAddrsGrp
		207		30		1	X			FilrAddrFrstTxt
		237		30		1	X			FilrAddrSecTxt
		267		28		1	X			FilrCtyNm
		295		30		1	X			FiPvstNm
		325		3		1	X			FilrCntryCd
		328		10		1	X			FilrPstlZipCd
	</pre>
	@see rccr.cobol.CobolRecord
*/

@SuppressWarnings({"all"})
public class IP6PRTSM extends CobolRecord
{
	private static HashMap h = new HashMap();

	private static TreeSet fields = new TreeSet(new MVComparator());

	private static int fieldCount = 0;
	private static void put( CobolField f ) {
		h.put(f.getName(), new MapValue( fieldCount++, f ));
	}

	private static void init0() {
		put(new CobolField("Prt18SummInfo",0,338,null,true));
		put(new CFNumeric("TransCd",0,4,null,0));
		put(new CobolField("RtnRcpntCntryCd",4,2,null,false));
		put(new CobolField("InfodecPsn",6,13,null,false));
		put(new CobolField("RtnSummTcd",19,9,null,false));
		put(new CobolField("RtnTcd",28,2,null,false));
		put(new CobolField("RtnTxYr",30,4,null,false));
		put(new CobolField("ReportingFiGrp",34,103,null,true));
		put(new CobolField("FiInfoDtyCd",34,1,null,false));
		put(new CobolField("FiDocRefId",35,40,null,false));
		put(new CobolField("FiCorrDocRefId",75,40,null,false));
		put(new CobolField("FiRsdCntryCd",115,2,null,false));
		put(new CobolField("FiGiin",117,20,null,false));
		put(new CobolField("ReportingFiNameGrp",137,70,null,true));
		put(new CobolField("FilrNmFrstTxt",137,35,null,false));
		put(new CobolField("FilrNmSecTxt",172,35,null,false));
		put(new CobolField("ReportingFiAddrsGrp",207,131,null,true));
		put(new CobolField("FilrAddrFrstTxt",207,30,null,false));
		put(new CobolField("FilrAddrSecTxt",237,30,null,false));
		put(new CobolField("FilrCtyNm",267,28,null,false));
		put(new CobolField("FiPvstNm",295,30,null,false));
		put(new CobolField("FilrCntryCd",325,3,null,false));
		put(new CobolField("FilrPstlZipCd",328,10,null,false));
	}

	static { 
		init0();
		fields.addAll(h.values());
	}

	public IP6PRTSM()
	{
		super(h, fields);
		rec = new byte[338];

		initialize();
	}

	public String getPrt18SummInfo() { 
		return getString("Prt18SummInfo");
	}

	public void setPrt18SummInfo( String val ) { 
		set( "Prt18SummInfo", val );
	}

	public int getTransCd() { 
		return getInt("TransCd");
	}

	public void setTransCd( int val ) { 
		set( "TransCd", val );
	}

	public String getRtnRcpntCntryCd() { 
		return getString("RtnRcpntCntryCd");
	}

	public void setRtnRcpntCntryCd( String val ) { 
		set( "RtnRcpntCntryCd", val );
	}

	public String getInfodecPsn() { 
		return getString("InfodecPsn");
	}

	public void setInfodecPsn( String val ) { 
		set( "InfodecPsn", val );
	}

	public String getRtnSummTcd() { 
		return getString("RtnSummTcd");
	}

	public void setRtnSummTcd( String val ) { 
		set( "RtnSummTcd", val );
	}

	public String getRtnTcd() { 
		return getString("RtnTcd");
	}

	public void setRtnTcd( String val ) { 
		set( "RtnTcd", val );
	}

	public String getRtnTxYr() { 
		return getString("RtnTxYr");
	}

	public void setRtnTxYr( String val ) { 
		set( "RtnTxYr", val );
	}

	public String getReportingFiGrp() { 
		return getString("ReportingFiGrp");
	}

	public void setReportingFiGrp( String val ) { 
		set( "ReportingFiGrp", val );
	}

	public String getFiInfoDtyCd() { 
		return getString("FiInfoDtyCd");
	}

	public void setFiInfoDtyCd( String val ) { 
		set( "FiInfoDtyCd", val );
	}

	public String getFiDocRefId() { 
		return getString("FiDocRefId");
	}

	public void setFiDocRefId( String val ) { 
		set( "FiDocRefId", val );
	}

	public String getFiCorrDocRefId() { 
		return getString("FiCorrDocRefId");
	}

	public void setFiCorrDocRefId( String val ) { 
		set( "FiCorrDocRefId", val );
	}

	public String getFiRsdCntryCd() { 
		return getString("FiRsdCntryCd");
	}

	public void setFiRsdCntryCd( String val ) { 
		set( "FiRsdCntryCd", val );
	}

	public String getFiGiin() { 
		return getString("FiGiin");
	}

	public void setFiGiin( String val ) { 
		set( "FiGiin", val );
	}

	public String getReportingFiNameGrp() { 
		return getString("ReportingFiNameGrp");
	}

	public void setReportingFiNameGrp( String val ) { 
		set( "ReportingFiNameGrp", val );
	}

	public String getFilrNmFrstTxt() { 
		return getString("FilrNmFrstTxt");
	}

	public void setFilrNmFrstTxt( String val ) { 
		set( "FilrNmFrstTxt", val );
	}

	public String getFilrNmSecTxt() { 
		return getString("FilrNmSecTxt");
	}

	public void setFilrNmSecTxt( String val ) { 
		set( "FilrNmSecTxt", val );
	}

	public String getReportingFiAddrsGrp() { 
		return getString("ReportingFiAddrsGrp");
	}

	public void setReportingFiAddrsGrp( String val ) { 
		set( "ReportingFiAddrsGrp", val );
	}

	public String getFilrAddrFrstTxt() { 
		return getString("FilrAddrFrstTxt");
	}

	public void setFilrAddrFrstTxt( String val ) { 
		set( "FilrAddrFrstTxt", val );
	}

	public String getFilrAddrSecTxt() { 
		return getString("FilrAddrSecTxt");
	}

	public void setFilrAddrSecTxt( String val ) { 
		set( "FilrAddrSecTxt", val );
	}

	public String getFilrCtyNm() { 
		return getString("FilrCtyNm");
	}

	public void setFilrCtyNm( String val ) { 
		set( "FilrCtyNm", val );
	}

	public String getFiPvstNm() { 
		return getString("FiPvstNm");
	}

	public void setFiPvstNm( String val ) { 
		set( "FiPvstNm", val );
	}

	public String getFilrCntryCd() { 
		return getString("FilrCntryCd");
	}

	public void setFilrCntryCd( String val ) { 
		set( "FilrCntryCd", val );
	}

	public String getFilrPstlZipCd() { 
		return getString("FilrPstlZipCd");
	}

	public void setFilrPstlZipCd( String val ) { 
		set( "FilrPstlZipCd", val );
	}

}