package ca.gc.cra.fxit.xmlt.transformation.cob2java.crs;
import ca.gc.ccra.rccr.cobol.*;
import java.util.*;

/** GENERATED BY COB2JAVA.
	MANUAL MAINTENANCE IS NOT RECOMMENDED

	<pre>
	Record Layout:

	  Offset  Length  Occ  Type Name
	  ======  ======  ===  ==== ==========================
		0		99		1	G	Prt18HdrRec
		0		4		1	9		TransCd
		4		8		1	9		Prt18SeqNbr
		12		1		1	X		Prt18RtnSummTcd
		13		8		1	9		RunDate
		21		8		1	9		RunTime
		29		4		1	X		RtnTxYr
		33		66		1	X		Filler
	</pre>
	@see rccr.cobol.CobolRecord
*/

@SuppressWarnings({"all"})
public class IP6PRTHD extends CobolRecord
{
	private static HashMap h = new HashMap();

	private static TreeSet fields = new TreeSet(new MVComparator());

	private static int fieldCount = 0;
	private static void put( CobolField f ) {
		h.put(f.getName(), new MapValue( fieldCount++, f ));
	}

	private static void init0() {
		put(new CobolField("Prt18HdrRec",0,99,null,true));
		put(new CFNumeric("TransCd",0,4,null,0));
		put(new CFNumeric("Prt18SeqNbr",4,8,null,0));
		put(new CobolField("Prt18RtnSummTcd",12,1,null,false));
		put(new CFNumeric("RunDate",13,8,null,0));
		put(new CFNumeric("RunTime",21,8,null,0));
		put(new CobolField("RtnTxYr",29,4,null,false));
	}

	static { 
		init0();
		fields.addAll(h.values());
	}

	public IP6PRTHD()
	{
		super(h, fields);
		rec = new byte[99];

		initialize();
	}

	public String getPrt18HdrRec() { 
		return getString("Prt18HdrRec");
	}

	public void setPrt18HdrRec( String val ) { 
		set( "Prt18HdrRec", val );
	}

	public int getTransCd() { 
		return getInt("TransCd");
	}

	public void setTransCd( int val ) { 
		set( "TransCd", val );
	}

	public int getPrt18SeqNbr() { 
		return getInt("Prt18SeqNbr");
	}

	public void setPrt18SeqNbr( int val ) { 
		set( "Prt18SeqNbr", val );
	}

	public String getPrt18RtnSummTcd() { 
		return getString("Prt18RtnSummTcd");
	}

	public void setPrt18RtnSummTcd( String val ) { 
		set( "Prt18RtnSummTcd", val );
	}

	public int getRunDate() { 
		return getInt("RunDate");
	}

	public void setRunDate( int val ) { 
		set( "RunDate", val );
	}

	public int getRunTime() { 
		return getInt("RunTime");
	}

	public void setRunTime( int val ) { 
		set( "RunTime", val );
	}

	public String getRtnTxYr() { 
		return getString("RtnTxYr");
	}

	public void setRtnTxYr( String val ) { 
		set( "RtnTxYr", val );
	}

}