//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.11 at 09:53:48 AM EST 
//


package ca.gc.cra.fxit.xmlt.transformation.jaxb.crs;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CrsMessageTypeIndic_EnumType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="CrsMessageTypeIndic_EnumType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="CRS701"/>
 *     &lt;enumeration value="CRS702"/>
 *     &lt;enumeration value="CRS703"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "CrsMessageTypeIndic_EnumType")
@XmlEnum
public enum CrsMessageTypeIndicEnumType {


    /**
     * The message contains new information
     * 
     */
    @XmlEnumValue("CRS701")
    CRS_701("CRS701"),

    /**
     * The message contains corrections for previously sent information
     * 
     */
    @XmlEnumValue("CRS702")
    CRS_702("CRS702"),

    /**
     * The message advises there is no data to report
     * 
     */
    @XmlEnumValue("CRS703")
    CRS_703("CRS703");
    private final String value;

    CrsMessageTypeIndicEnumType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static CrsMessageTypeIndicEnumType fromValue(String v) {
        for (CrsMessageTypeIndicEnumType c: CrsMessageTypeIndicEnumType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
