//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.10 at 03:45:42 PM EDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "urn:oecd:ties:stffatcatypes:v1", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package ca.gc.cra.fxit.xmlt.transformation.jaxb.ftc;
