//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.13 at 01:38:40 PM EST 
//


package ca.gc.cra.fxit.xmlt.transformation.jaxb.metadata;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for BinaryEncodingSchemeCdType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="BinaryEncodingSchemeCdType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="NONE"/>
 *     &lt;enumeration value="BASE64"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "BinaryEncodingSchemeCdType")
@XmlEnum
public enum BinaryEncodingSchemeCdType {


    /**
     * No Special Encoding
     * 
     */
    NONE("NONE"),

    /**
     * Base64 Encoded
     * 
     */
    @XmlEnumValue("BASE64")
    BASE_64("BASE64");
    private final String value;

    BinaryEncodingSchemeCdType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static BinaryEncodingSchemeCdType fromValue(String v) {
        for (BinaryEncodingSchemeCdType c: BinaryEncodingSchemeCdType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
