//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.13 at 01:38:40 PM EST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "urn:oecd:ctssenderfilemetadata", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.UNQUALIFIED,
xmlns = { 
		@javax.xml.bind.annotation.XmlNs(namespaceURI = "urn:oecd:ctssenderfilemetadata", prefix = "")
}
		)
package ca.gc.cra.fxit.xmlt.transformation.jaxb.metadata;
